# Deploy a Grafana instance managed by Grafana Operator.
# Skip if you already have a Grafana; then ensure it has label dashboards: nfl-wallet (or change instanceSelector in datasource/dashboard).
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-nfl-wallet
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    dashboards: nfl-wallet
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
  deployment:
    spec:
      replicas: 1
