# ---------------------------------------------------------------------------
# NFL Wallet - ApplicationSet for East cluster (no ACM, no labels)
# Generates 3 Applications (dev, test, prod). Edit server below for east cluster.
# ---------------------------------------------------------------------------
# server: use https://kubernetes.default.svc for in-cluster, or your east API server URL
# ---------------------------------------------------------------------------

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nfl-wallet-east
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - path: nfl-wallet-dev
                  namespace: nfl-wallet-dev
                - path: nfl-wallet-test
                  namespace: nfl-wallet-test
                - path: nfl-wallet-prod
                  namespace: nfl-wallet-prod
          - list:
              elements:
                - server: https://kubernetes.default.svc
  template:
    metadata:
      name: "nfl-wallet-east-{{path}}"
      labels:
        app.kubernetes.io/part-of: application-lifecycle
        app.kubernetes.io/managed-by: argocd
        cluster: east
    spec:
      project: default
      source:
        repoURL: https://github.com/maximilianoPizarro/nfl-wallet-gitops.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - helm-values.yaml
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
