# ---------------------------------------------------------------------------
# Observability - ApplicationSet for East + West (hub view)
# Deploys observability stack (Grafana Operator, dashboard, datasource) to hub.
# Grafana visualizes metrics from NFL Wallet (dev, test, prod) on both east and west clusters.
# Plain YAML (no Helm). Datasource typically points to Promxy/ACM Observability.
# ---------------------------------------------------------------------------

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-east-west
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - path: observability
                  namespace: observability
          - list:
              elements:
                - server: https://kubernetes.default.svc
  template:
    metadata:
      name: "observability-east-west"
      labels:
        app.kubernetes.io/part-of: application-lifecycle
        app.kubernetes.io/managed-by: argocd
        cluster: east-west
    spec:
      project: default
      source:
        repoURL: https://github.com/maximilianoPizarro/nfl-wallet-gitops.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
