# ---------------------------------------------------------------------------
# NFL Wallet - ACM Placements + ApplicationSet (GitOps)
# Hub: cluster-g62mw.dynamic.redhatworkshops.io
# East/West (managed): cluster-s6krm.s6krm.sandbox3480.opentlc.com (adjust if west has different domain)
# Deploys nfl-wallet to namespaces nfl-wallet-dev, nfl-wallet-test, nfl-wallet-prod on BOTH east and west.
# ---------------------------------------------------------------------------
# Usage: Apply on the hub (ACM) with OpenShift GitOps installed.
# Requires: ConfigMap acm-placement in openshift-gitops with cluster decisions.
# Label managed clusters: east with region=east (and optionally purpose=development/testing/production),
# west with region=west. Placements select by region so dev/test/prod deploy to both east and west.
# Cluster domain: east = cluster-s6krm.s6krm.sandbox3480.opentlc.com; set westClusterDomain if different.
# ---------------------------------------------------------------------------

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nfl-wallet-dev-east-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - east
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nfl-wallet-dev-west-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - west
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nfl-wallet-test-east-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - east
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nfl-wallet-test-west-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - west
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nfl-wallet-prod-east-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - east
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nfl-wallet-prod-west-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - west
---
# ApplicationSet: one Application per (env × region). East cluster domain = cluster-s6krm...; west = same or set below.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nfl-wallet
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: nfl-wallet
                  namespace: nfl-wallet-dev
                  path: nfl-wallet-dev
                  placementName: nfl-wallet-dev-east-placement
                  clusterDomain: cluster-s6krm.s6krm.sandbox3480.opentlc.com
                - appName: nfl-wallet
                  namespace: nfl-wallet-dev
                  path: nfl-wallet-dev
                  placementName: nfl-wallet-dev-west-placement
                  clusterDomain: cluster-s6krm.s6krm.sandbox3480.opentlc.com  # change if west has different domain
                - appName: nfl-wallet
                  namespace: nfl-wallet-test
                  path: nfl-wallet-test
                  placementName: nfl-wallet-test-east-placement
                  clusterDomain: cluster-s6krm.s6krm.sandbox3480.opentlc.com
                - appName: nfl-wallet
                  namespace: nfl-wallet-test
                  path: nfl-wallet-test
                  placementName: nfl-wallet-test-west-placement
                  clusterDomain: cluster-s6krm.s6krm.sandbox3480.opentlc.com  # change if west has different domain
                - appName: nfl-wallet
                  namespace: nfl-wallet-prod
                  path: nfl-wallet-prod
                  placementName: nfl-wallet-prod-east-placement
                  clusterDomain: cluster-s6krm.s6krm.sandbox3480.opentlc.com
                - appName: nfl-wallet
                  namespace: nfl-wallet-prod
                  path: nfl-wallet-prod
                  placementName: nfl-wallet-prod-west-placement
                  clusterDomain: cluster-s6krm.s6krm.sandbox3480.opentlc.com  # change if west has different domain
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: "{{placementName}}"
              requeueAfterSeconds: 30
  template:
    metadata:
      name: "{{appName}}-{{name}}"
      labels:
        velero.io/exclude-from-backup: "true"
        app.kubernetes.io/part-of: application-lifecycle
        app.kubernetes.io/managed-by: argocd
        apps.open-cluster-management.io/cluster-set: global
        cluster.open-cluster-management.io/placement: "{{placementName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/maximilianoPizarro/nfl-wallet-gitops.git
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - helm-values.yaml
          parameters:
            - name: nfl-wallet.clusterDomain
              value: "{{clusterDomain}}"
            - name: nfl-wallet.gateway.route.host
              value: "{{namespace}}.apps.{{clusterDomain}}"
            - name: nfl-wallet.webapp.route.host
              value: "webapp-{{namespace}}.apps.{{clusterDomain}}"
            - name: nfl-wallet.blueGreen.hostname
              value: "nfl-wallet-canary.apps.{{clusterDomain}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
