# API keys para AuthPolicy (connectivity-link). Secrets en el namespace de la app con label api=<namespace>.
# AuthPolicy usa allNamespaces: true. Usar Sealed Secrets / External Secrets en prod.
# Usamos kuadrantApiKeys.enabled para evitar duplicado con el chart (api-keys-secret.yaml).
{{- $nfl := index .Values "nfl-wallet" -}}
{{- if or ((index $nfl "kuadrantApiKeys" | default dict).enabled | default false) ($nfl.apiKeys.enabled | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-api-keys
  namespace: {{ .Release.Namespace }}
  labels:
    api: {{ .Release.Namespace }}
    kuadrant.io/managed-by: authorino
    authorino.kuadrant.io/managed-by: authorino
stringData:
  api_key: {{ $nfl.apiKeys.customers | quote }}
  api-key-bills: {{ $nfl.apiKeys.bills | quote }}
  api-key-customers: {{ $nfl.apiKeys.customers | quote }}
  api-key-raiders: {{ $nfl.apiKeys.raiders | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-api-keys-customers
  namespace: {{ .Release.Namespace }}
  labels:
    api: {{ .Release.Namespace }}
    kuadrant.io/managed-by: authorino
    authorino.kuadrant.io/managed-by: authorino
stringData:
  api_key: {{ $nfl.apiKeys.customers | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-api-keys-bills
  namespace: {{ .Release.Namespace }}
  labels:
    api: {{ .Release.Namespace }}
    kuadrant.io/managed-by: authorino
    authorino.kuadrant.io/managed-by: authorino
stringData:
  api_key: {{ $nfl.apiKeys.bills | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-api-keys-raiders
  namespace: {{ .Release.Namespace }}
  labels:
    api: {{ .Release.Namespace }}
    kuadrant.io/managed-by: authorino
    authorino.kuadrant.io/managed-by: authorino
stringData:
  api_key: {{ $nfl.apiKeys.raiders | quote }}
{{- end }}
