# API key Secrets for Kuadrant AuthPolicy (selector api=<namespace>).
# Each Secret must have data.api_key and label api={{ .Release.Namespace }}.
# Set nfl-wallet.apiKeys.customers, .bills, .raiders in helm-values (or override via Sealed Secrets).
{{- if (index .Values "nfl-wallet").apiKeys.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-customers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/component: api-key
    api: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.customers | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-bills
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/component: api-key
    api: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.bills | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-raiders
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/component: api-key
    api: {{ .Release.Namespace }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.raiders | default "" | quote }}
{{- end }}
