# API key Secrets for Kuadrant AuthPolicy. Created in kuadrant-system so Authorino can read them
# when allNamespaces is false. Only created when nfl-wallet.apiKeys.enabled is true.
{{ if (index .Values "nfl-wallet").apiKeys.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-customers-test
  namespace: {{ default "kuadrant-system" (index .Values "nfl-wallet").kuadrantNamespace }}
  labels:
    api: {{ .Release.Namespace }}
    authorino.kuadrant.io/managed-by: {{ default "authorino" (index .Values "nfl-wallet").authorinoManagedBy }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.customers | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-bills-test
  namespace: {{ default "kuadrant-system" (index .Values "nfl-wallet").kuadrantNamespace }}
  labels:
    api: {{ .Release.Namespace }}
    authorino.kuadrant.io/managed-by: {{ default "authorino" (index .Values "nfl-wallet").authorinoManagedBy }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.bills | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-raiders-test
  namespace: {{ default "kuadrant-system" (index .Values "nfl-wallet").kuadrantNamespace }}
  labels:
    api: {{ .Release.Namespace }}
    authorino.kuadrant.io/managed-by: {{ default "authorino" (index .Values "nfl-wallet").authorinoManagedBy }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.raiders | quote }}
{{ end }}
