# AuthPolicy (connectivity-link): API key solo para /api-bills, /api-customers, /api-raiders.
# Frontend (/) y Swagger permiten acceso anónimo.
{{- if (index .Values "nfl-wallet").authPolicy.enabled | default true }}
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: nfl-wallet-test-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: auth-policy
    app.kubernetes.io/part-of: nfl-wallet
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ default "nfl-wallet-gateway" (index .Values "nfl-wallet").gatewayPolicyGatewayName }}
  rules:
    authentication:
      "anonymous":
        priority: 1
        when:
          - predicate: 'request.method == "OPTIONS" || request.path.contains("swagger") || request.path.contains("api-docs") || request.path.endsWith("/swagger") || request.path == "/swagger" || (!request.path.startsWith("/api-bills") && !request.path.startsWith("/api-customers") && !request.path.startsWith("/api-raiders"))'
        anonymous: {}
      "api-key":
        priority: 0
        when:
          - predicate: 'request.method != "OPTIONS" && !(request.path.contains("swagger") || request.path.contains("api-docs") || request.path.endsWith("/swagger") || request.path == "/swagger") && (request.path.startsWith("/api-bills") || request.path.startsWith("/api-customers") || request.path.startsWith("/api-raiders"))'
        apiKey:
          selector:
            matchLabels:
              api: {{ .Release.Namespace }}
            allNamespaces: true
          credentials:
            customHeader:
              name: X-Api-Key
{{- end }}
