# Istio Waypoint proxy (ambient mesh) – optional. Clears Kiali KIA1317 when using ambient mode.
# Only created when nfl-wallet.waypoint.enabled is true. Requires: Gateway API CRDs, Istio ambient;
# namespace should be labeled istio.io/dataplane-mode=ambient and optionally istio.io/use-waypoint=waypoint.
{{- if index .Values "nfl-wallet" "waypoint" "enabled" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: {{ .Release.Namespace }}
  labels:
    istio.io/waypoint-for: {{ default "service" (index .Values "nfl-wallet" "waypoint" "for") }}
    app.kubernetes.io/component: waypoint
    app.kubernetes.io/part-of: nfl-wallet
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
{{- end }}