# API key Secrets for Kuadrant AuthPolicy (selector api=<namespace>).
# Authorino only watches Secrets that match its secretLabelSelector (e.g. authorino.kuadrant.io/managed-by).
# Each Secret: data.api_key, label api={{ .Release.Namespace }}, and label for Authorino instance.
{{- if (index .Values "nfl-wallet").apiKeys.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-customers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/component: api-key
    api: {{ .Release.Namespace }}
    authorino.kuadrant.io/managed-by: {{ (index .Values "nfl-wallet").authorinoManagedByLabel | default "authorino" }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.customers | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-bills
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/component: api-key
    api: {{ .Release.Namespace }}
    authorino.kuadrant.io/managed-by: {{ (index .Values "nfl-wallet").authorinoManagedByLabel | default "authorino" }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.bills | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-apikey-raiders
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nfl-wallet
    app.kubernetes.io/component: api-key
    api: {{ .Release.Namespace }}
    authorino.kuadrant.io/managed-by: {{ (index .Values "nfl-wallet").authorinoManagedByLabel | default "authorino" }}
type: Opaque
stringData:
  api_key: {{ (index .Values "nfl-wallet").apiKeys.raiders | default "" | quote }}
{{- end }}
