# ---------------------------------------------------------------------------
# Optional: Argo CD cluster secrets for east and west (use on the HUB if
# GitOpsCluster does not create them and you see "there are no clusters with
# this name: west").
#
# If west Applications show "the server has asked for the client to provide
# credentials", the west cluster secret has invalid/expired credentials. Update
# the secret with a valid bearerToken (see below) or recreate it from this file.
#
# Apply on the HUB: kubectl apply -f docs/argocd-cluster-secrets-manual.yaml
# You must set the bearerToken for each cluster (e.g. from ACM managed cluster
# import or a service account token that can access the managed cluster API).
#
# Get token for a managed cluster (run on hub). Option A: from the managed cluster's kubeconfig secret:
#   oc get secret <cluster-name>-import -n open-cluster-management-agent -o jsonpath='{.data.import-config}' | base64 -d
#   Then extract the token from the kubeconfig. Option B: use the cluster's admin kubeconfig and run:
#   argocd cluster add <context-from-kubeconfig> --name east --server https://api....
#   That will create the secret for you; or copy the bearerToken from the generated secret.
#
# Update existing west secret with new token (replace TOKEN with a valid token for west cluster):
#   kubectl patch secret -n openshift-gitops -l argocd.argoproj.io/secret-type=cluster --type='json' -p='[{"op":"replace","path":"/data/config","value":"'$(echo -n '{"tlsClientConfig":{"insecure":true},"bearerToken":"TOKEN"}' | base64 -w0)'"}]}'
#   Or edit: kubectl edit secret <cluster-west-secret-name> -n openshift-gitops (config is base64).
#   After updating the secret, restart the application controller to reload cluster credentials:
#   kubectl rollout restart statefulset/openshift-gitops-application-controller -n openshift-gitops
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: cluster-east
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: east
  server: https://api.cluster-s6krm.s6krm.sandbox3480.opentlc.com:6443
  config: '{"tlsClientConfig":{"insecure":true},"bearerToken":"<REPLACE_WITH_EAST_CLUSTER_TOKEN>"}'
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-west
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: west
  server: https://api.cluster-9nvg4.dynamic.redhatworkshops.io:6443
  config: '{"tlsClientConfig":{"insecure":true},"bearerToken":"<REPLACE_WITH_WEST_CLUSTER_TOKEN>"}'
---
