# ---------------------------------------------------------------------------
# Argo CD health customizations: HTTPRoute and AuthPolicy → Healthy
# ---------------------------------------------------------------------------
# APPLY ON THE HUB (merge into existing argocd-cm; does not remove other keys):
#   kubectl patch configmap argocd-cm -n openshift-gitops --type merge --patch-file docs/argocd-cm-health-customizations.yaml
# Then restart Argo CD so it reloads the config:
#   kubectl rollout restart deployment/openshift-gitops-server -n openshift-gitops
# If health still does not update, restart the application controller (name varies by version):
#   kubectl get deploy,statefulset -n openshift-gitops
#   kubectl rollout restart statefulset/argocd-application-controller -n openshift-gitops
#   # or: kubectl rollout restart deployment/argocd-application-controller -n openshift-gitops
# ---------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: openshift-gitops
data:
  # Gateway API HTTPRoute: treat as Healthy so app health is not stuck Progressing
  resource.customizations.health.gateway.networking.k8s.io_HTTPRoute: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Accepted"
    return hs
  # Kuadrant AuthPolicy (apiVersion: kuadrant.io/v1): treat as Healthy so app health is not stuck Progressing
  resource.customizations.health.kuadrant.io_AuthPolicy: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "Accepted"
    return hs
