# ---------------------------------------------------------------------------
# Optional: Argo CD cluster secrets for east and west (use on the HUB if
# GitOpsCluster does not create them and you see "there are no clusters with
# this name: west" or east).
#
# Sync fails with "failed to discover server resources ... Unauthorized" or
# "the server has asked for the client to provide credentials" when the
# cluster secret (east or west) has invalid/expired bearerToken. Update the
# secret for that cluster and restart the application controller (see below).
#
# Apply on the HUB: kubectl apply -f docs/argocd-cluster-secrets-manual.yaml
# You must set the bearerToken for each cluster (e.g. from ACM managed cluster
# import or a service account token that can access the managed cluster API).
#
# Get token for a managed cluster (run on hub). Option A: from the managed cluster's kubeconfig secret:
#   oc get secret <cluster-name>-import -n open-cluster-management-agent -o jsonpath='{.data.import-config}' | base64 -d
#   Then extract the token from the kubeconfig. Option B: use the cluster's admin kubeconfig and run:
#   argocd cluster add <context-from-kubeconfig> --name east --server https://api....
#   That will create the secret for you; or copy the bearerToken from the generated secret.
#
# Update existing secret (east or west) with new token:
#   1) Get token on MANAGED cluster (east or west) — create a long-lived token for the Argo CD SA:
#      oc login https://api.<east-domain>:6443
#      oc create namespace openshift-gitops --dry-run=client -o yaml | oc apply -f -
#      oc create serviceaccount openshift-gitops-argocd-application-controller -n openshift-gitops --dry-run=client -o yaml | oc apply -f -
#      oc create token openshift-gitops-argocd-application-controller -n openshift-gitops --duration=87600h
#      (87600h = 10 years; copy the printed token. If the API rejects, try 8760h for 1 year.)
#      echo $TOKEN   # use this in step 2
#   2) On the HUB, patch the secret (replace TOKEN with the value from step 1):
#      kubectl patch secret cluster-east -n openshift-gitops --type='json' -p='[{"op":"replace","path":"/data/config","value":"'$(echo -n '{"tlsClientConfig":{"insecure":true},"bearerToken":"TOKEN"}' | base64 -w0)'"}]}'
#      (Use cluster-west and west token for west.)
#   3) Restart the application controller:
#      kubectl rollout restart statefulset/openshift-gitops-application-controller -n openshift-gitops
#   Or edit manually: kubectl edit secret cluster-east -n openshift-gitops — set data.config to base64 of {"tlsClientConfig":{"insecure":true},"bearerToken":"<token>"}
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: cluster-east
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: east
  server: https://api.cluster-h625z.h625z.sandbox613.opentlc.com:6443
  config: '{"tlsClientConfig":{"insecure":true},"bearerToken":"<REPLACE_WITH_EAST_CLUSTER_TOKEN>"}'
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-west
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: west
  server: https://api.cluster-2l9nd.dynamic.redhatworkshops.io:6443
  config: '{"tlsClientConfig":{"insecure":true},"bearerToken":"<REPLACE_WITH_WEST_CLUSTER_TOKEN>"}'
---
